name: gtel
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  shelf: ^1.2.0
  shelf_router: ^1.1.0
  postgres: ^2.2.0
  dart_jsonwebtoken: ^2.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6